# Question 1:

For this question you will need to dowload the `customer_database` zip folder from Canvas.

Import the `customer_demographics.csv` and `customer_transactions` dataset using pandas. Using the `customer_transactions` dataset create an RFM matrix. Call this data `rfm`.

Merge `rfm` to `customer_demographics.csv` dataset using an appropriate key.

Print the first 5 rows of the data. Inspect the data - clean the data if necessary.

In [2]:
import pandas as pd
from datetime import datetime

customer_demographics= pd.read_csv ("customer_demographics.csv" )
customer_transactions = pd.read_csv ("customer_transactions.csv" )

customer_transactions.head()

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
0,1,2,2950,25/02/2017,False,Approved,Solex,Standard,medium,medium,71.49,$53.62,41245.0
1,2,3,3120,21/05/2017,True,Approved,Trek Bicycles,Standard,medium,large,2091.47,$388.92,41701.0
2,3,37,402,16/10/2017,False,Approved,OHM Cycles,Standard,low,medium,1793.43,$248.82,36361.0
3,4,88,3135,31/08/2017,False,Approved,Norco Bicycles,Standard,medium,medium,1198.46,$381.10,36145.0
4,5,78,787,01/10/2017,True,Approved,Giant Bicycles,Standard,medium,large,1765.30,$709.48,42226.0

In [3]:
rfm = customer_transactions.loc[:, ["customer_id", "transaction_date", "list_price"]].assign(transaction_date=lambda d: pd.to_datetime(d.transaction_date, format="%d/%m/%Y")).groupby(["customer_id"], as_index=False).agg(
    Recency=('transaction_date', 'nunique'),
    MonetaryValue=('list_price', 'sum'),
    LastTransactionDate=('transaction_date', 'max')
).assign(
    RecencyValue=lambda d: (pd.to_datetime('2017-12-31') - d.LastTransactionDate),
    RecencyInt=lambda d: d.RecencyValue.dt.days
)

merged_data = pd.merge(customer_demographics, rfm, left_on="customer_id", right_on="customer_id", how="inner")


merged_data.head()

,customer_id,name,gender,past_3_years_bike_related_purchases,DOB,age,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,tenure,Recency,MonetaryValue,LastTransactionDate,RecencyValue,RecencyInt
0,34,Jephthah Bachmann,U,59,1843-12-21,123.0,Legal Assistant,IT,Affluent Customer,N,No,20.0,9,13133.00,2017-09-19,103 days,103
1,144,Jory Barrabeale,U,71,NaN,123.0,Environmental Tech,IT,Mass Customer,N,No,NaN,8,8961.14,2017-12-24,7 days,7
2,168,Reggie Broggetti,U,8,NaN,123.0,General Manager,IT,Affluent Customer,N,Yes,NaN,9,10135.25,2017-08-16,137 days,137
3,267,Edgar Buckler,U,53,NaN,123.0,NaN,IT,High Net Worth,N,No,NaN,4,5029.25,2017-08-22,131 days,131
4,290,Giorgio Kevane,U,42,NaN,123.0,Senior Sales Associate,IT,Mass Customer,N,No,NaN,5,5912.93,2017-12-19,12 days,12

In [4]:
print(rfm)

      customer_id  Recency  MonetaryValue LastTransactionDate RecencyValue  \
0               1       11        9084.45          2017-12-23       8 days
1               2        3        4149.07          2017-08-24     129 days
2               3        8        9888.23          2017-09-19     103 days
3               4        2        1047.72          2017-06-18     196 days
4               5        6        5903.20          2017-12-14      17 days
...           ...      ...            ...                 ...          ...
3489         3497        3        3744.07          2017-11-08      53 days
3490         3498        6        5177.06          2017-08-25     128 days
3491         3499        7        7673.48          2017-11-09      52 days
3492         3500        6        4922.41          2017-08-08     145 days
3493         5034        3        1519.92          2017-10-07      85 days

      RecencyInt
0              8
1            129
2            103
3            196
4             17
...          ...
3489          53
3490         128
3491          52
3492         145
3493          85

[3494 rows x 6 columns]

In [5]:
merged_data = (
    customer_transactions.merge(rfm, how = 'inner', on = 'customer_id')
)
print(merged_data)

       transaction_id  product_id  customer_id transaction_date online_order  \
0                   1           2         2950       25/02/2017        False
1               11065           1         2950       16/10/2017        False
2               18923          62         2950       26/04/2017        False
3                   2           3         3120       21/05/2017         True
4                6862           4         3120       05/10/2017        False
...               ...         ...          ...              ...          ...
19995           19854          68          130       02/02/2017         True
19996           17966          17         2789       06/12/2017        False
19997           18462          80         2789       20/06/2017        False
19998           17981          69         3446       26/12/2017         True
19999           18165          86         3446       03/12/2017        False

      order_status           brand product_line product_class product_size  \
0         Approved           Solex     Standard        medium       medium
1         Approved  Giant Bicycles     Standard        medium       medium
2         Approved           Solex     Standard        medium       medium
3         Approved   Trek Bicycles     Standard        medium        large
4         Approved  Giant Bicycles     Standard          high       medium
...            ...             ...          ...           ...          ...
19995     Approved      OHM Cycles     Standard        medium       medium
19996     Approved           Solex     Standard          high       medium
19997     Approved      OHM Cycles      Touring           low       medium
19998     Approved  Giant Bicycles         Road        medium       medium
19999     Approved      OHM Cycles     Standard        medium       medium

       list_price standard_cost  product_first_sold_date  Recency  \
0           71.49        $53.62                  41245.0        3
1         1403.50       $954.82                  37659.0        3
2          478.16       $298.72                  40487.0        3
3         2091.47       $388.92                  41701.0        7
4         1129.13       $677.48                  40649.0        7
...           ...           ...                      ...      ...
19995     1636.90        $44.71                  40410.0        2
19996     1024.66       $614.80                  35378.0        2
19997     1073.07       $933.84                  42226.0        2
19998      792.90       $594.68                  33879.0        2
19999      235.63       $125.07                  38206.0        2

       MonetaryValue LastTransactionDate RecencyValue  RecencyInt
0            1953.15          2017-10-16      76 days          76
1            1953.15          2017-10-16      76 days          76
2            1953.15          2017-10-16      76 days          76
3            7351.70          2017-12-10      21 days          21
4            7351.70          2017-12-10      21 days          21
...              ...                 ...          ...         ...
19995        3340.42          2017-10-15      77 days          77
19996        2097.73          2017-12-06      25 days          25
19997        2097.73          2017-12-06      25 days          25
19998        1028.53          2017-12-26       5 days           5
19999        1028.53          2017-12-26       5 days           5

[20000 rows x 18 columns]

In [6]:
print(merged_data.isnull().sum())

transaction_id               0
product_id                   0
customer_id                  0
transaction_date             0
online_order               360
order_status                 0
brand                      197
product_line               197
product_class              197
product_size               197
list_price                   0
standard_cost              197
product_first_sold_date    197
Recency                      0
MonetaryValue                0
LastTransactionDate          0
RecencyValue                 0
RecencyInt                   0
dtype: int64

In [7]:
print(merged_data.head(5))

   transaction_id  product_id  customer_id transaction_date online_order  \
0               1           2         2950       25/02/2017        False
1           11065           1         2950       16/10/2017        False
2           18923          62         2950       26/04/2017        False
3               2           3         3120       21/05/2017         True
4            6862           4         3120       05/10/2017        False

  order_status           brand product_line product_class product_size  \
0     Approved           Solex     Standard        medium       medium
1     Approved  Giant Bicycles     Standard        medium       medium
2     Approved           Solex     Standard        medium       medium
3     Approved   Trek Bicycles     Standard        medium        large
4     Approved  Giant Bicycles     Standard          high       medium

   list_price standard_cost  product_first_sold_date  Recency  MonetaryValue  \
0       71.49        $53.62                  41245.0        3        1953.15
1     1403.50       $954.82                  37659.0        3        1953.15
2      478.16       $298.72                  40487.0        3        1953.15
3     2091.47       $388.92                  41701.0        7        7351.70
4     1129.13       $677.48                  40649.0        7        7351.70

  LastTransactionDate RecencyValue  RecencyInt
0          2017-10-16      76 days          76
1          2017-10-16      76 days          76
2          2017-10-16      76 days          76
3          2017-12-10      21 days          21
4          2017-12-10      21 days          21

# Question 2

Suppose you hypothesize that affluent customers on average spend more than high net worth customers. Conduct a suitable hypothesis test to check if this is true.

In [8]:
merged_data_demo_tran = (
    customer_transactions.merge(customer_demographics, how = 'inner', on = 'customer_id'))

In [9]:
merged_data_demo_tran.head()

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,...,gender,past_3_years_bike_related_purchases,DOB,age,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,tenure
0,1,2,2950,25/02/2017,False,Approved,Solex,Standard,medium,medium,...,Male,19,1955-01-11,68.0,Software Engineer I,Financial Services,Mass Customer,N,Yes,10.0
1,11065,1,2950,16/10/2017,False,Approved,Giant Bicycles,Standard,medium,medium,...,Male,19,1955-01-11,68.0,Software Engineer I,Financial Services,Mass Customer,N,Yes,10.0
2,18923,62,2950,26/04/2017,False,Approved,Solex,Standard,medium,medium,...,Male,19,1955-01-11,68.0,Software Engineer I,Financial Services,Mass Customer,N,Yes,10.0
3,2,3,3120,21/05/2017,True,Approved,Trek Bicycles,Standard,medium,large,...,Female,89,1979-02-04,44.0,Clinical Specialist,Health,Mass Customer,N,Yes,10.0
4,6862,4,3120,05/10/2017,False,Approved,Giant Bicycles,Standard,high,medium,...,Female,89,1979-02-04,44.0,Clinical Specialist,Health,Mass Customer,N,Yes,10.0

In [10]:
print(merged_data.columns)

Index(['transaction_id', 'product_id', 'customer_id', 'transaction_date',
       'online_order', 'order_status', 'brand', 'product_line',
       'product_class', 'product_size', 'list_price', 'standard_cost',
       'product_first_sold_date', 'Recency', 'MonetaryValue',
       'LastTransactionDate', 'RecencyValue', 'RecencyInt'],
      dtype='object')

In [11]:
import scipy.stats as stats


filtered_data = merged_data[merged_data['Recency'].notna()]


affluent_data = filtered_data[filtered_data['Recency'] == 'Affluent']['MonetaryValue']
high_net_worth_data = filtered_data[filtered_data['Recency'] == 'High Net Worth']['MonetaryValue']


t_stat, p_value = stats.ttest_ind(affluent_data, high_net_worth_data, equal_var=False)

# Set the significance level (alpha)
alpha = 0.05


if p_value < alpha:
    print("Reject the null hypothesis:")
    print("The average spending of affluent customers is different from that of high net worth customers.")
else:
    print("Fail to reject the null hypothesis:")
    print("The average spending of affluent customers is equal to that of high net worth customers.")

Fail to reject the null hypothesis:
The average spending of affluent customers is equal to that of high net worth customers.

# Question 3

Run a linear regression model to estimate the impact of `gender`, `age`, and `past_3_years_bike_related_purchases` for customers on`frequency` of transactions. Interpret the coefficients.

In [13]:
import pandas as pd
from statsmodels.formula.api import ols


cust_dem = pd.read_csv("https://raw.githubusercontent.com/shovonhasan1/mktanalytics/main/customer_demographics.csv", index_col=False)
cus_tran = pd.read_csv("https://raw.githubusercontent.com/shovonhasan1/mktanalytics/main/customer_transactions.csv", index_col=False)


cust_data = pd.merge(cust_dem, cus_tran, on="customer_id")

cust_data["frequency"] = cust_data.groupby("customer_id")["transaction_id"].transform("count")


model = ols("frequency ~ gender + age + past_3_years_bike_related_purchases", data=cust_data).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              frequency   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.000
Method:                 Least Squares   F-statistic:                     3.485
Date:                Fri, 10 Nov 2023   Prob (F-statistic):            0.00751
Time:                        00:14:15   Log-Likelihood:                -45312.
No. Observations:               19997   AIC:                         9.063e+04
Df Residuals:                   19992   BIC:                         9.067e+04
Df Model:                           4
Covariance Type:            nonrobust
=======================================================================================================
                                          coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
Intercept                               6.7218      0.072     93.970      0.000       6.582       6.862
gender[T.Male]                          0.0567      0.033      1.697      0.090      -0.009       0.122
gender[T.U]                             0.2534      0.152      1.673      0.094      -0.044       0.550
age                                    -0.0002      0.001     -0.146      0.884      -0.003       0.002
past_3_years_bike_related_purchases    -0.0016      0.001     -2.695      0.007      -0.003      -0.000
==============================================================================
Omnibus:                      384.006   Durbin-Watson:                   0.346
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              404.705
Skew:                           0.345   Prob(JB):                     1.32e-88
Kurtosis:                       2.905   Cond. No.                         684.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

The intercept value of 6.7218 represents the estimated baseline purchase frequency for the reference category of the gender variable, assuming all other variables remain at 0.

The gender coefficient for males (0.0567) implies that, with all other factors held constant, males tend to have a purchase frequency 0.0567 units higher than individuals in the baseline gender category.

The age coefficient (-0.0002) indicates that for each additional year of age, the purchase frequency decreases by 0.0002 units, while keeping all other factors constant.

The coefficient for past_3_years_bike_related_purchases (-0.0016) suggests that for each additional past bike-related purchase, the purchase frequency decreases by 0.0016 units, assuming all other variables remain constant.

# Question 4

1. Add `job_industry_category` and `wealth_segment` to the above model. Interpret the coefficients.
2. Next, add the interaction of `wealth_segment` and `gender` to the above model. Rerun the model and interpret the coefficients.
3. Lastly, add the interaction of `age` and `gender` to the above model. Rerun the model and interpret the coefficients.

In [14]:
model = ols("frequency ~ gender + age + past_3_years_bike_related_purchases + job_industry_category + wealth_segment", data=cust_data).fit()

In [15]:
model = ols("frequency ~ gender * wealth_segment + age + past_3_years_bike_related_purchases + job_industry_category", data=cust_data).fit()

In [16]:
model = ols("frequency ~ gender * age + past_3_years_bike_related_purchases + job_industry_category + wealth_segment", data=cust_data).fit()

In [17]:
print(model)

<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x79429ede2b60>

# Question 5

Use the recency, frequency and monetary value to perform k means clustering.
1. Generate 4 clusters.
2. Use the cluster centers to come up with suitable names for the clusters
3. Differentiate the identity and behavior of the clusters

In [24]:
from sklearn.cluster import KMeans
import pandas as pd


features = merged_data[['Recency', 'MonetaryValue', 'RecencyInt']]

kmeans = KMeans(n_clusters=4, random_state=42)
labels = kmeans.fit_predict(features)


merged_data_with_labels = merged_data.assign(Cluster=labels)


print(merged_data_with_labels.head())


cluster_centers = pd.DataFrame(kmeans.cluster_centers_, columns=['Recency', 'MonetaryValue', 'RecencyInt'])
cluster_centers['Cluster'] = range(4)
print("\nCluster Centers:")
print(cluster_centers)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

   transaction_id  product_id  customer_id transaction_date online_order  \
0               1           2         2950       25/02/2017        False
1           11065           1         2950       16/10/2017        False
2           18923          62         2950       26/04/2017        False
3               2           3         3120       21/05/2017         True
4            6862           4         3120       05/10/2017        False

  order_status           brand product_line product_class product_size  \
0     Approved           Solex     Standard        medium       medium
1     Approved  Giant Bicycles     Standard        medium       medium
2     Approved           Solex     Standard        medium       medium
3     Approved   Trek Bicycles     Standard        medium        large
4     Approved  Giant Bicycles     Standard          high       medium

   list_price standard_cost  product_first_sold_date  Recency  MonetaryValue  \
0       71.49        $53.62                  41245.0        3        1953.15
1     1403.50       $954.82                  37659.0        3        1953.15
2      478.16       $298.72                  40487.0        3        1953.15
3     2091.47       $388.92                  41701.0        7        7351.70
4     1129.13       $677.48                  40649.0        7        7351.70

  LastTransactionDate RecencyValue  RecencyInt  Cluster
0          2017-10-16      76 days          76        2
1          2017-10-16      76 days          76        2
2          2017-10-16      76 days          76        2
3          2017-12-10      21 days          21        0
4          2017-12-10      21 days          21        0

Cluster Centers:
     Recency  MonetaryValue  RecencyInt  Cluster
0   6.089402    6524.076533   54.607538        0
1  10.086184   13001.811564   31.561972        1
2   4.196305    3772.146098   71.802071        2
3   7.978317    9335.109523   43.195143        3

Cluster 0:

Low Recency (6.09): Customers in this cluster made transactions relatively recently.

High MonetaryValue ($6524.08): Customers in this cluster have a high total monetary value of transactions.

Medium RecencyInt (54.61): The average number of days since the last transaction is moderate.



Cluster 1:

Moderate Recency (10.09): Customers in this cluster made transactions with a moderate recency.

High MonetaryValue ($13001.81): Customers in this cluster have the highest total monetary value of transactions.

Low RecencyInt (31.56): The average number of days since the last transaction is relatively low.



Cluster 2:

Very Low Recency (4.20): Customers in this cluster made transactions very recently.

Low MonetaryValue ($3772.15): Customers in this cluster have a low total monetary value of transactions.

High RecencyInt (71.80): The average number of days since the last transaction is high.



Cluster 3:

Moderate Recency (7.98): Customers in this cluster made transactions with a moderate recency.

Moderate MonetaryValue ($9335.11): Customers in this cluster have a moderate total monetary value of transactions.

Moderate RecencyInt (43.20): The average number of days since the last transaction is moderate.